;(function () {
;(function () {
(function(){if(!window.b24form){window.b24form=function(e){b24form.forms=b24form.forms||[];b24form.forms.push(e);if(e.ref&&b24form.Loader&&!this.loaded){this.loaded=true;b24form.Loader.loadJs(e.ref,true)}}}if(window.b24form.Loader){return}function e(){this.requested=false;this.queue=[]}e.prototype={run:function(e){e=e||{};var o=e.resources||{};this.queue.push(e.form);if(!this.requested){var t=this.loadApp.bind(this,o.app);this.requested=true;if(o.polyfill&&!this.checkPolyfills()){this.loadJs(o.polyfill,true,t)}else{t()}}this.loadForms()},loadApp:function(e){if(!e){return}window.b24form.App?this.loadForms():this.loadJs(e,true,this.loadForms.bind(this))},loadForms:function(){if(!this.checkPolyfills()){return}if(!window.b24form.App){return}var e=this.queue;this.queue=[];e.forEach(this.loadForm,this)},loadForm:function(e){b24form.App.initFormScript24(e)},checkPolyfills:function(){return window.fetch&&window.Request&&window.Response&&window.Promise&&Object.assign&&Array.prototype.find&&Array.prototype.includes},loadJs:function(e,o,t){var i=document.createElement("SCRIPT");i.setAttribute("type","text/javascript");i.setAttribute("async","");if(o){i.setAttribute("src",e+"?"+(Date.now()/864e5|0));if(t){i.onload=t}this.appendToHead(i)}else{i.appendChild(document.createTextNode(e));this.appendToHead(i)}},appendToHead:function(e){(document.getElementsByTagName("head")[0]||document.documentElement).appendChild(e)}};window.b24form.Loader=new e})();
//# sourceMappingURL=https://holdings.bitrix24.com/bitrix/js/crm/site/form/embed/unit/script.map.js

window.b24form.Loader.run({"form":{"id":"2","sec":"z3gqmq","lang":"en","address":"https:\/\/holdings.bitrix24.com","views":{"click":{"type":"panel","position":"right","vertical":"bottom"},"auto":{"type":"popup","position":"center","vertical":"bottom","delay":"3"}},"data":{"language":"en","design":{"style":"modern","shadow":true,"font":{"uri":"","family":"Open Sans"},"border":{"bottom":true,"top":false,"left":false,"right":false},"color":{"primary":"#57302eff","primaryText":"#ffffffff","text":"#000000ff","background":"#ffffffff","fieldBorder":"#0000000c","fieldBackground":"#00000000","fieldFocusBackground":"#00000000"}},"title":"Discover Your Future at Wechi","desc":"Get floor plans, pricing, and availability \u2014 start your journey today.","buttonCaption":"Contact Me","useSign":false,"date":{"dateFormat":"MM\/DD\/YYYY","dateTimeFormat":"MM\/DD\/YYYY H:MI:SS T","sundayFirstly":true},"currency":{"code":"RUB","title":"Russian Ruble","format":"\u0026#8381;#"},"fields":[{"id":"CONTACT_NAME","name":"CONTACT_NAME","label":"First Name","visible":true,"required":true,"multiple":false,"valueType":"","type":"name","placeholder":null,"value":"","items":[],"hint":"","hintOnFocus":false,"autocomplete":true,"bigPic":false,"size":null,"contentTypes":null},{"id":"CONTACT_LAST_NAME","name":"CONTACT_LAST_NAME","label":"Last Name","visible":true,"required":true,"multiple":false,"valueType":"","type":"last-name","placeholder":null,"value":"","items":[],"hint":"","hintOnFocus":false,"autocomplete":true,"bigPic":false,"size":null,"contentTypes":null},{"id":"CONTACT_PHONE","name":"CONTACT_PHONE","label":"Phone","visible":true,"required":true,"multiple":false,"valueType":"WORK","type":"phone","placeholder":null,"value":"","items":[],"hint":"","hintOnFocus":false,"autocomplete":true,"bigPic":false,"size":null,"contentTypes":null},{"id":"CONTACT_EMAIL","name":"CONTACT_EMAIL","label":"E-mail","visible":true,"required":true,"multiple":false,"valueType":"WORK","type":"email","placeholder":null,"value":"","items":[],"hint":"","hintOnFocus":false,"autocomplete":true,"bigPic":false,"size":null,"contentTypes":null}],"agreements":[],"dependencies":[],"captcha":{"service":"google","recaptcha":{"use":false},"yandexCaptcha":{"use":false}}}},"resources":{"app":"https:\/\/cdn.bitrix24.com\/b34763753\/crm\/form\/app.js","polyfill":"https:\/\/cdn.bitrix24.com\/b34763753\/crm\/form\/polyfill.js"}});
})();


})();